import Head from 'next/head';
import Alumni from '@/components/Home/Alumni';
import CampusLife from '@/components/Home/CampusLife';
import Career from '@/components/Home/Career';
import Faculty from '@/components/Home/Faculty';
import InternationalStudents from '@/components/Home/InternationalStudents';
import Programs from '@/components/Home/Programs';
import Scholarship from '@/components/Home/Scholarship';
import HeroSection from '@/components/Home/Hero';
import NewsLetter from '@/components/Home/NewsLetter';
import 'swiper/css';
import 'swiper/css/navigation';


export default function Home() {
  return (
    <>
      <Head>
        <title>SummerField University</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <main className="  flex flex-col gap-6 min-h-[calc(100vh-300px)]">
          <Alumni></Alumni>
          <CampusLife></CampusLife>
          <Career></Career>
          <Faculty></Faculty>
          <InternationalStudents></InternationalStudents>
          <Programs></Programs>
          <Scholarship></Scholarship>
        </main>
      </>
    </>
  );
}
