import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Alumni from '@/components/Home/Alumni'
import CampusLife from '@/components/Home/CampusLife'
import Career from '@/components/Home/Career'
import Faculty from '@/components/Home/Faculty'
import InternationalStudents from '@/components/Home/InternationalStudents'
import Programs from '@/components/Home/Programs'
import Scholarship from '@/components/Home/Scholarship'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>University</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Alumni></Alumni>
        <CampusLife></CampusLife>
        <Career></Career>
        <Faculty></Faculty>
        <InternationalStudents></InternationalStudents>
        <Programs></Programs>
        <Scholarship></Scholarship>
      </>
    </>
  )
}
